import React from "react"

export const ContentMenuSectionDivider = () => (
  <svg
    width="220"
    height="1"
    viewBox="0 0 220 1"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className="flex-shrink-0"
  >
    <g clipPath="url(#clip0_53867_23674)">
      <g clipPath="url(#clip1_53867_23674)">
        <rect
          x="1.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="5.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="9.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="13.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="17.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="21.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="25.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="29.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="33.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="37.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="41.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="45.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="49.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="53.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="57.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="61.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="65.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="69.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="73.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="77.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="81.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="85.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="89.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="93.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="97.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="101.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="105.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="109.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="113.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="117.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="121.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="125.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="129.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="133.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="137.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="141.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="145.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="149.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="153.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="157.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="161.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="165.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="169.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="173.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="177.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="181.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="185.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="189.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="193.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="197.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="201.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="205.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="209.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="213.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
        <rect
          x="217.5"
          width="1"
          height="1"
          className="fill-medusa-fg-disabled"
        />
      </g>
    </g>
    <defs>
      <clipPath id="clip0_53867_23674">
        <rect width="220" height="1" className="fill-medusa-fg-base" />
      </clipPath>
      <clipPath id="clip1_53867_23674">
        <rect width="220" height="1" className="fill-medusa-fg-base" />
      </clipPath>
    </defs>
  </svg>
)
