get:
  operationId: GetTranslationsSettings
  summary: List Translations
  description: >-
    Retrieve a list of translations. The translations can be filtered by fields
    such as `id`. The translations can also be sorted or paginated.
  x-authenticated: true
  parameters:
    - name: entity_type
      in: query
      description: The translation's entity type.
      required: false
      schema:
        type: string
        title: entity_type
        description: The translation's entity type.
    - name: is_active
      in: query
      description: The translation's is active.
      required: false
      schema:
        type: boolean
        title: is_active
        description: The translation's is active.
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  x-codeSamples:
    - lang: JavaScript
      label: JS SDK
      source:
        $ref: ../code_samples/JavaScript/admin_translations_settings/get.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/admin_translations_settings/get.sh
  tags:
    - Translations
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminTranslationSettingsResponse.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-since: 2.12.3
  x-featureFlag: translation
