"team: medusa":
  - "@olivermrbl"
  - "@srindom"
  - "@adrien2p"
  - "@riqwan"
  - "@fPolic"
  - "@shahednasser"
  - "@carlos-r-l-rodrigues"
  - "@VariableVic"
  - "@kasperkristensen"
  - "@pKorsholm"
  - "@sradevski"
  - "@edast"
  - "@thetutlage"
