export const indexSettingsDefault = {
  products: {
    indexSettings: {
      searchableAttributes: ["title", "description", "material", "tags"],
      attributesToRetrieve: [
        "id",
        "title",
        "handle",
        "thumbnail",
        "subtitle",
        "tags",
      ],
    },
  },
  categories: {
    indexSettings: {
      searchableAttributes: ["name", "description"],
      attributesToRetrieve: ["id", "name", "handle", "thumbnail"],
    },
    transformer: (item) => ({
      objectID: item.id,
      name: item.name,
      handle: item.handle,
      thumbnail: item.thumbnail,
      description: item.description,
    }),
  },
  tags: {
    indexSettings: {
      searchableAttributes: ["name", "description"],
      attributesToRetrieve: ["id", "name"],
    },
  },
}

export const indexSettingsCustomProductTransformer = {
  ...indexSettingsDefault,
  products: {
    ...indexSettingsDefault.products,
    transformer: (item) => ({
      objectID: item.id,
      title: item.title,
      handle: item.handle,
      subtitle: item.subtitle,
      tags: item.tags,
      thumbnail: item.thumbnail,
    }),
  },
}

export const product = {
  id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
  title: "WOMEN'S HEAVY TERRY CROPPED CLUB JACKET",
  subtitle: null,
  status: "published",
  external_id: "AAHVT3529",
  description:
    "498.0 G/SqM;71% Cotton. 29% Polyester;Cropped body;Cadet collar;Contrast striped (body color/white) rib cuffs. collar and bottom band;Front metallic snaps;Side seam;Double-satin razor label;",
  handle: "womens-heavy-terry-cropped-club-jacket-aahvt3529",
  is_giftcard: false,
  discountable: true,
  thumbnail: "https:/thumbnail-url.com/aahvt3529-8-1699112940007.jpg",
  collection_id: null,
  type_id: null,
  weight: null,
  length: null,
  height: null,
  width: null,
  hs_code: null,
  origin_country: "Poland",
  mid_code: null,
  material: null,
  created_at: "2023-11-04T15:48:59.667Z",
  updated_at: "2023-11-04T15:48:59.667Z",
  deleted_at: null,
  metadata: {},
  translations: null,
  working_area: [],
  top_pick: false,
  collection: null,
  images: [],
  options: [
    {
      type: "color",
      id: "opt_01HEDGBWNJ6D9T2W9F90NEKPND",
      created_at: "2023-11-04T15:48:59.667Z",
      updated_at: "2023-11-04T15:48:59.667Z",
      deleted_at: null,
      title: "Color",
      product_id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
      metadata: null,
      values: [
        {
          id: "optval_01HEDGBWPSX965MJ88BH59JEJ4",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "Black w Black/White",
          option_id: "opt_01HEDGBWNJ6D9T2W9F90NEKPND",
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
          metadata: null,
        },
      ],
    },
    {
      type: "size",
      id: "opt_01HEDGBWNMT9PBSJVFYKN2RKEZ",
      created_at: "2023-11-04T15:48:59.667Z",
      updated_at: "2023-11-04T15:48:59.667Z",
      deleted_at: null,
      title: "Size",
      product_id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
      metadata: null,
      values: [
        {
          id: "optval_01HEDGBWPSEA6KRJE41093Q0YM",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "XL",
          option_id: "opt_01HEDGBWNMT9PBSJVFYKN2RKEZ",
          variant_id: "variant_01HEDGBWPS3NA855JPRFZ19XER",
          metadata: null,
        },
      ],
    },
  ],
  product_reviews: [],
  profiles: [],
  tags: [],
  type: null,
  variants: [
    {
      id: "variant_01HEDGBWPS8EZDQASX93006H9W",
      created_at: "2023-11-04T15:48:59.667Z",
      updated_at: "2023-11-04T15:48:59.667Z",
      deleted_at: null,
      title: "Black w Black/White / L",
      product_id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
      sku: "aahvt3529bl/bl/wh-l",
      barcode: "00191675151835",
      ean: null,
      upc: null,
      variant_rank: 0,
      inventory_quantity: 91,
      allow_backorder: false,
      manage_inventory: true,
      hs_code: null,
      origin_country: null,
      mid_code: null,
      material: null,
      weight: null,
      length: null,
      height: null,
      width: null,
      metadata: {
        images: [],
      },
      options: [
        {
          id: "optval_01HEDGBWPSX965MJ88BH59JEJ4",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "Black w Black/White",
          option_id: "opt_01HEDGBWNJ6D9T2W9F90NEKPND",
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
          metadata: null,
        },
        {
          id: "optval_01HEDGBWPSESBZ0PGXEM2SXSD6",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "L",
          option_id: "opt_01HEDGBWNMT9PBSJVFYKN2RKEZ",
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
          metadata: null,
        },
      ],
      prices: [
        {
          id: "ma_01HEDGBWR46C7PC3XGCM7FJ6GY",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          currency_code: "eur",
          amount: 278,
          min_quantity: null,
          max_quantity: null,
          price_list_id: null,
          region_id: null,
          price_list: null,
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
        },
      ],
      original_price: null,
      calculated_price: null,
      original_price_incl_tax: null,
      calculated_price_incl_tax: null,
      original_tax: null,
      calculated_tax: null,
      tax_rates: null,
    },
  ],
}

export const transformedProductDefault = {
  id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
  title: "WOMEN'S HEAVY TERRY CROPPED CLUB JACKET",
  subtitle: null,
  status: "published",
  external_id: "AAHVT3529",
  description:
    "498.0 G/SqM;71% Cotton. 29% Polyester;Cropped body;Cadet collar;Contrast striped (body color/white) rib cuffs. collar and bottom band;Front metallic snaps;Side seam;Double-satin razor label;",
  handle: "womens-heavy-terry-cropped-club-jacket-aahvt3529",
  is_giftcard: false,
  discountable: true,
  thumbnail: "https:/thumbnail-url.com/aahvt3529-8-1699112940007.jpg",
  collection_id: null,
  type_id: null,
  weight: null,
  length: null,
  height: null,
  width: null,
  hs_code: null,
  origin_country: "Poland",
  mid_code: null,
  material: null,
  created_at: "2023-11-04T15:48:59.667Z",
  updated_at: "2023-11-04T15:48:59.667Z",
  deleted_at: null,
  metadata: {},
  translations: null,
  working_area: [],
  top_pick: false,
  collection: null,
  images: [],
  options: [
    {
      type: "color",
      id: "opt_01HEDGBWNJ6D9T2W9F90NEKPND",
      created_at: "2023-11-04T15:48:59.667Z",
      updated_at: "2023-11-04T15:48:59.667Z",
      deleted_at: null,
      title: "Color",
      product_id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
      metadata: null,
      values: [
        {
          id: "optval_01HEDGBWPSX965MJ88BH59JEJ4",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "Black w Black/White",
          option_id: "opt_01HEDGBWNJ6D9T2W9F90NEKPND",
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
          metadata: null,
        },
      ],
    },
    {
      type: "size",
      id: "opt_01HEDGBWNMT9PBSJVFYKN2RKEZ",
      created_at: "2023-11-04T15:48:59.667Z",
      updated_at: "2023-11-04T15:48:59.667Z",
      deleted_at: null,
      title: "Size",
      product_id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
      metadata: null,
      values: [
        {
          id: "optval_01HEDGBWPSEA6KRJE41093Q0YM",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "XL",
          option_id: "opt_01HEDGBWNMT9PBSJVFYKN2RKEZ",
          variant_id: "variant_01HEDGBWPS3NA855JPRFZ19XER",
          metadata: null,
        },
      ],
    },
  ],
  product_reviews: [],
  profiles: [],
  tags: [],
  type: null,
  variants: [
    {
      id: "variant_01HEDGBWPS8EZDQASX93006H9W",
      created_at: "2023-11-04T15:48:59.667Z",
      updated_at: "2023-11-04T15:48:59.667Z",
      deleted_at: null,
      title: "Black w Black/White / L",
      product_id: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
      sku: "aahvt3529bl/bl/wh-l",
      barcode: "00191675151835",
      ean: null,
      upc: null,
      variant_rank: 0,
      inventory_quantity: 91,
      allow_backorder: false,
      manage_inventory: true,
      hs_code: null,
      origin_country: null,
      mid_code: null,
      material: null,
      weight: null,
      length: null,
      height: null,
      width: null,
      metadata: {
        images: [],
      },
      options: [
        {
          id: "optval_01HEDGBWPSX965MJ88BH59JEJ4",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "Black w Black/White",
          option_id: "opt_01HEDGBWNJ6D9T2W9F90NEKPND",
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
          metadata: null,
        },
        {
          id: "optval_01HEDGBWPSESBZ0PGXEM2SXSD6",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          value: "L",
          option_id: "opt_01HEDGBWNMT9PBSJVFYKN2RKEZ",
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
          metadata: null,
        },
      ],
      prices: [
        {
          id: "ma_01HEDGBWR46C7PC3XGCM7FJ6GY",
          created_at: "2023-11-04T15:48:59.667Z",
          updated_at: "2023-11-04T15:48:59.667Z",
          deleted_at: null,
          currency_code: "eur",
          amount: 278,
          min_quantity: null,
          max_quantity: null,
          price_list_id: null,
          region_id: null,
          price_list: null,
          variant_id: "variant_01HEDGBWPS8EZDQASX93006H9W",
        },
      ],
      original_price: null,
      calculated_price: null,
      original_price_incl_tax: null,
      calculated_price_incl_tax: null,
      original_tax: null,
      calculated_tax: null,
      tax_rates: null,
    },
  ],
  objectID: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
  type_value: null,
  collection_title: null,
  collection_handle: null,
  tags_value: [],
  categories: [],
  variant_sku: ["aahvt3529bl/bl/wh-l"],
  variant_title: ["Black w Black/White / L"],
  variant_upc: [],
  variant_ean: [],
  variant_mid_code: [],
  variant_hs_code: [],
  variant_options: [],
  variant_options_value: ["Black w Black/White", "L"],
}

export const transformedProductCustom = {
  objectID: "prod_01HEDGBWMKXBVSZ2EYBBQQNFFA",
  title: "WOMEN'S HEAVY TERRY CROPPED CLUB JACKET",
  handle: "womens-heavy-terry-cropped-club-jacket-aahvt3529",
  subtitle: null,
  tags: [],
  thumbnail: "https:/thumbnail-url.com/aahvt3529-8-1699112940007.jpg",
}

export const tag = {
  id: "tag_01HEDGBWQZJZJZJZJZJZJZJZJZ",
  name: "tag",
  description: "lorem ipsum",
}

export const category = {
  featured: true,
  thumbnail:
    "https://jd-static.fra1.digitaloceanspaces.com/aarsa8380-white-a1-1698057246164-1699112818998.jpg",
  parent_category: null,
  category_children: [],
  id: "pcat_01HEDG5KX5BDV2X96WNT4F8M20",
  created_at: "2023-11-04T15:45:34.623Z",
  updated_at: "2023-11-04T15:46:59.236Z",
  name: "Clothing",
  description: "Great clothing for every occasion! ",
  handle: "clothing",
  is_active: true,
  is_internal: false,
  parent_category_id: null,
  rank: 0,
}

export const transformedCategory = {
  objectID: "pcat_01HEDG5KX5BDV2X96WNT4F8M20",
  name: "Clothing",
  description: "Great clothing for every occasion! ",
  handle: "clothing",
  thumbnail:
    "https://jd-static.fra1.digitaloceanspaces.com/aarsa8380-white-a1-1698057246164-1699112818998.jpg",
}
