import dedent from "ts-dedent"

/**
 * Creates the content for the virtual entry file. This file is used to
 * bundle the extension(s) in a format that the admin dashboard is able
 * to load.
 */
export async function createVirtualEntry(
  extensions: string[],
  identifier: string
): Promise<string | null> {
  if (!extensions?.length) {
    return null
  }

  const banner = dedent`
    /**
     * This file is automatically generated by the Medusa Admin SDK.
     * Do not edit this file directly, or delete it.
     */
  `

  const imports = extensions.map((ext, i) => {
    return `import ext${i}, { config as config${i}} from "${ext}"`
  })

  const body = dedent`
    const entry = {
      identifier: "${identifier}",
      extensions: [
        ${extensions
          .map((_, i) => `{ Component: ext${i}, config: config${i} }`)
          .join(",\n")}
      ]
    }
  `

  const exportStatement = `export default entry`

  return dedent`
    ${banner}
    ${imports.join("\n")}

    ${body}

    ${exportStatement}
  `
}
