import {
  PRODUCT_CUSTOM_FIELD_DISPLAY_PATHS,
  PRODUCT_CUSTOM_FIELD_DISPLAY_ZONES,
  PRODUCT_CUSTOM_FIELD_FORM_CONFIG_PATHS,
  PRODUCT_CUSTOM_FIELD_FORM_FIELD_PATHS,
  PRODUCT_CUSTOM_FIELD_FORM_TABS,
  PRODUCT_CUSTOM_FIELD_FORM_ZONES,
  PRODUCT_CUSTOM_FIELD_LINK_PATHS,
  PRODUCT_CUSTOM_FIELD_MODEL,
} from "./product"

export const CUSTOM_FIELD_MODELS = [PRODUCT_CUSTOM_FIELD_MODEL] as const

export const CUSTOM_FIELD_CONTAINER_ZONES = [
  ...PRODUCT_CUSTOM_FIELD_DISPLAY_ZONES,
] as const

export const CUSTOM_FIELD_FORM_ZONES = [
  ...PRODUCT_CUSTOM_FIELD_FORM_ZONES,
] as const

export const CUSTOM_FIELD_FORM_TABS = [
  ...PRODUCT_CUSTOM_FIELD_FORM_TABS,
] as const

export const CUSTOM_FIELD_FORM_CONFIG_PATHS = [
  ...PRODUCT_CUSTOM_FIELD_FORM_CONFIG_PATHS,
] as const

export const CUSTOM_FIELD_FORM_FIELD_PATHS = [
  ...PRODUCT_CUSTOM_FIELD_FORM_FIELD_PATHS,
] as const

export const CUSTOM_FIELD_DISPLAY_PATHS = [
  ...PRODUCT_CUSTOM_FIELD_DISPLAY_PATHS,
] as const

export const CUSTOM_FIELD_LINK_PATHS = [
  ...PRODUCT_CUSTOM_FIELD_LINK_PATHS,
] as const
