export const defaultStoreCartFields = [
  "id",
  "currency_code",
  "email",
  "created_at",
  "updated_at",
  "items.id",
  "items.variant_id",
  "items.product_id",
  "items.product_title",
  "items.product_description",
  "items.product_subtitle",
  "items.product_type",
  "items.product_collection",
  "items.product_handle",
  "items.variant_sku",
  "items.variant_barcode",
  "items.variant_title",
  "items.created_at",
  "items.updated_at",
  "items.title",
  "items.quantity",
  "items.unit_price",
  "items.tax_lines.id",
  "items.tax_lines.description",
  "items.tax_lines.code",
  "items.tax_lines.rate",
  "items.tax_lines.provider_id",
  "items.adjustments.id",
  "items.adjustments.code",
  "items.adjustments.amount",
  "customer.id",
  "customer.email",
  "customer.groups.id",
  "shipping_methods.tax_lines.id",
  "shipping_methods.tax_lines.description",
  "shipping_methods.tax_lines.code",
  "shipping_methods.tax_lines.rate",
  "shipping_methods.tax_lines.provider_id",
  "shipping_methods.shipping_option_id",
  "shipping_methods.amount",
  "shipping_methods.adjustments.id",
  "shipping_methods.adjustments.code",
  "shipping_methods.adjustments.amount",
  "shipping_address.id",
  "shipping_address.first_name",
  "shipping_address.last_name",
  "shipping_address.address_1",
  "shipping_address.address_2",
  "shipping_address.city",
  "shipping_address.postal_code",
  "shipping_address.country_code",
  "shipping_address.region_code",
  "shipping_address.province",
  "shipping_address.phone",
  "billing_address.id",
  "billing_address.first_name",
  "billing_address.last_name",
  "billing_address.address_1",
  "billing_address.address_2",
  "billing_address.city",
  "billing_address.postal_code",
  "billing_address.country_code",
  "billing_address.region_code",
  "billing_address.phone",
  "region.id",
  "region.name",
  "region.currency_code",
  "sales_channel_id",

  // TODO: To be updated when payment sessions are introduces in the Rest API
  "payment_collection.id",
  "payment_collection.amount",
  "payment_collection.payment_sessions",
]

export const defaultStoreCartRelations = [
  "items",
  "items.tax_lines",
  "items.adjustments",
  "region",
  "customer",
  "customer.groups",
  "shipping_address",
  "billing_address",
  "shipping_methods",
  "shipping_methods.tax_lines",
  "shipping_methods.adjustments",
]

export const allowedRelations = [
  "items",
  "items.tax_lines",
  "items.adjustments",
  "region",
  "customer",
  "customer.groups",
  "shipping_address",
  "billing_address",
  "shipping_methods",
  "shipping_methods.tax_lines",
  "shipping_methods.adjustments",
  "sales_channel",
]

export const retrieveTransformQueryConfig = {
  defaultFields: defaultStoreCartFields,
  defaultRelations: defaultStoreCartRelations,
  allowedRelations: defaultStoreCartRelations,
  isList: false,
}
