title: Product Tag
description: Product Tags can be added to Products for easy filtering and grouping.
x-resourceId: product_tag
required:
  - value
properties:
  id:
    type: string
    description: The product tag's ID
    example: ptag_01G8K2MTMG9168F2B70S1TAVK3
  value:
    description: The value that the Product Tag represents
    type: string
    example: Pants
  created_at:
    type: string
    description: The date with timezone at which the resource was created.
    format: date-time
  updated_at:
    type: string
    description: The date with timezone at which the resource was updated.
    format: date-time
  deleted_at:
    type: string
    description: The date with timezone at which the resource was deleted.
    format: date-time
  metadata:
    type: object
    description: An optional key-value map with additional details
    example:
      car: white
