%%{
    init: {
      'theme': 'base',
      'themeVariables': {
        'background': '#F9FAFB',
        'primaryColor': '#FFFFFF',
        'primaryTextColor': '#030712',
        'primaryBorderColor': '#D1D5DB',
        'lineColor': '#11181C',
        'fontFamily': 'Inter',
        'fontSize': '13px',
        'clusterBkg': 'transparent',
        'clusterBorder': 'transparent'
      }
    }
  }%%
  	flowchart LR
  	subgraph
		startStep["`Start
  	input: {#quot;name#quot;:#quot;string#quot;}
  	`"]
	step1[step-1]
	step2[step-2]
	end
	subgraph
	step3[step-3]
	step4[step-4]
	endStep["`End
  	output: {#quot;message#quot;:#quot;string#quot;}
  	`"]
	startStep --> step1 --> step2 --> step3 --> step4 --> endStep