get:
  operationId: GetProductsProduct
  summary: Get a Product
  description: Retrieves a Product.
  parameters:
    - in: path
      name: id
      required: true
      description: The id of the Product.
      schema:
        type: string
    - in: query
      name: sales_channel_id
      description: The sales channel used when fetching the product.
      schema:
        type: string
    - in: query
      name: cart_id
      description: The ID of the customer's cart.
      schema:
        type: string
    - in: query
      name: region_id
      description: >-
        The ID of the region the customer is using. This is helpful to ensure
        correct prices are retrieved for a region.
      schema:
        type: string
    - in: query
      name: fields
      description: (Comma separated) Which fields should be included in the result.
      schema:
        type: string
    - in: query
      name: expand
      description: >-
        (Comma separated) Which fields should be expanded in each product of the
        result.
      schema:
        type: string
    - in: query
      name: currency_code
      style: form
      explode: false
      description: >-
        The 3 character ISO currency code to set prices based on. This is
        helpful to ensure correct prices are retrieved for a currency.
      schema:
        type: string
        externalDocs:
          url: https://en.wikipedia.org/wiki/ISO_4217#Active_codes
          description: See a list of codes.
  x-codegen:
    method: retrieve
    queryParams: StoreGetProductsProductParams
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/get.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/get.sh
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/StoreProductsRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
