import {
  AcademicCapSolid,
  Adjustments,
  ArrowDownLeftMini,
  ArrowDownTray,
  ArrowUpRightOnBox,
  ArrowUturnLeft,
  BarsThree,
  BellAlert,
  BellAlertSolid,
  Bolt,
  BoltSolid,
  BookOpen,
  Bug,
  BugAntSolid,
  BuildingStorefront,
  BuildingTax,
  BuildingsSolid,
  Calendar,
  CashSolid,
  Channels,
  ChannelsSolid,
  CheckCircleSolid,
  CheckMini,
  ChevronDoubleLeftMiniSolid,
  ChevronUpDown,
  CircleDottedLine,
  CircleMiniSolid,
  CircleStack,
  CircleStackSolid,
  ClockSolidMini,
  CloudArrowUp,
  CogSixTooth,
  CogSixToothSolid,
  CommandLine,
  CommandLineSolid,
  ComponentSolid,
  ComputerDesktop,
  ComputerDesktopSolid,
  CreditCardSolid,
  CubeSolid,
  CurrencyDollar,
  CurrencyDollarSolid,
  Discord,
  DocumentText,
  DocumentTextSolid,
  EllipseMiniSolid,
  ExclamationCircle,
  ExclamationCircleSolid,
  FlyingBox,
  Folder,
  FolderOpen,
  Gatsby,
  GiftSolid,
  GlobeEurope,
  GlobeEuropeSolid,
  InformationCircleSolid,
  JavascriptEx,
  Key,
  KeySolid,
  LightBulb,
  LightBulbSolid,
  Linkedin,
  MagnifyingGlass,
  Map,
  Moon,
  Newspaper,
  PencilSquareSolid,
  Puzzle,
  ReactJsEx,
  ReceiptPercent,
  RocketLaunch,
  Server,
  ServerSolid,
  ServerStack,
  ServerStackSolid,
  ShoppingCart,
  ShoppingCartSolid,
  Sidebar,
  Sparkles,
  SparklesSolid,
  SquareTwoStackSolid,
  SquaresPlus,
  SquaresPlusSolid,
  Star,
  StarSolid,
  Stripe,
  Sun,
  SwatchSolid,
  TagSolid,
  Tools,
  ToolsSolid,
  Twitter,
  User,
  UsersSolid,
  XCircleSolid,
  XMark,
  XMarkMini,
  PhotoSolid,
} from "@medusajs/icons"
import IconPuzzleSolid from "./PuzzleSolid"
import IconNextjs from "./Nextjs"
import IconFlagMini from "./FlagMini"
import IconBeaker from "./Beaker"
import IconGitHub from "./GitHub"

export default {
  "academic-cap-solid": AcademicCapSolid,
  adjustments: Adjustments,
  alert: ExclamationCircleSolid,
  "arrow-down-left-mini": ArrowDownLeftMini,
  "arrow-down-tray": ArrowDownTray,
  "back-arrow": ArrowUturnLeft,
  "bars-three": BarsThree,
  beaker: IconBeaker,
  bell: BellAlert,
  "bell-alert-solid": BellAlertSolid,
  bolt: Bolt,
  "bolt-solid": BoltSolid,
  "book-open": BookOpen,
  bug: Bug,
  "bug-ant-solid": BugAntSolid,
  "building-solid": BuildingsSolid,
  "building-storefront": BuildingStorefront,
  "building-tax": BuildingTax,
  calendar: Calendar,
  "cash-solid": CashSolid,
  "channels-solid": ChannelsSolid,
  channels: Channels,
  "check-circle-solid": CheckCircleSolid,
  "check-mini": CheckMini,
  "chevron-double-left-mini-solid": ChevronDoubleLeftMiniSolid,
  "chevron-up-down": ChevronUpDown,
  "circle-dotted-line": CircleDottedLine,
  "circle-mini-solid": CircleMiniSolid,
  "circle-stack": CircleStack,
  "circle-stack-solid": CircleStackSolid,
  "clock-solid-mini": ClockSolidMini,
  close: XMark,
  "cloud-arrow-up": CloudArrowUp,
  "cog-six-tooth": CogSixTooth,
  "cog-six-tooth-solid": CogSixToothSolid,
  "command-line": CommandLine,
  "command-line-solid": CommandLineSolid,
  "component-solid": ComponentSolid,
  "computer-desktop": ComputerDesktop,
  "computer-desktop-solid": ComputerDesktopSolid,
  copy: SquareTwoStackSolid,
  "credit-card-solid": CreditCardSolid,
  "cube-solid": CubeSolid,
  "currency-dollar": CurrencyDollar,
  "currency-dollar-solid": CurrencyDollarSolid,
  "dark-mode": Moon,
  discord: Discord,
  "document-text": DocumentText,
  "document-text-solid": DocumentTextSolid,
  "ellipse-mini-solid": EllipseMiniSolid,
  "exclamation-circle-solid": ExclamationCircleSolid,
  "external-link": ArrowUpRightOnBox,
  "flying-box": FlyingBox,
  folder: Folder,
  "folder-open": FolderOpen,
  gatsby: Gatsby,
  "gift-solid": GiftSolid,
  "flag-mini": IconFlagMini,
  github: IconGitHub,
  "globe-europe": GlobeEurope,
  "globe-europe-solid": GlobeEuropeSolid,
  "information-circle-solid": InformationCircleSolid,
  javascript: JavascriptEx,
  key: Key,
  "key-solid": KeySolid,
  "light-bulb": LightBulb,
  "light-bulb-solid": LightBulbSolid,
  "light-mode": Sun,
  linkedin: Linkedin,
  "magnifying-glass": MagnifyingGlass,
  map: Map,
  newspaper: Newspaper,
  nextjs: IconNextjs,
  "pencil-square-solid": PencilSquareSolid,
  "photo-solid": PhotoSolid,
  puzzle: Puzzle,
  // TODO change once available in Icons package
  "puzzle-solid": IconPuzzleSolid,
  react: ReactJsEx,
  "receipt-percent": ReceiptPercent,
  report: ExclamationCircle,
  "rocket-launch": RocketLaunch,
  server: Server,
  "server-solid": ServerSolid,
  "server-stack": ServerStack,
  "server-stack-solid": ServerStackSolid,
  "shopping-cart": ShoppingCart,
  "shopping-cart-solid": ShoppingCartSolid,
  sidebar: Sidebar,
  sparkles: Sparkles,
  "sparkles-solid": SparklesSolid,
  "squares-plus": SquaresPlus,
  "squares-plus-solid": SquaresPlusSolid,
  star: Star,
  "star-solid": StarSolid,
  stripe: Stripe,
  "swatch-solid": SwatchSolid,
  "tag-solid": TagSolid,
  tools: Tools,
  "tools-solid": ToolsSolid,
  twitter: Twitter,
  user: User,
  "users-solid": UsersSolid,
  "x-circle-solid": XCircleSolid,
  "x-mark": XMark,
  "x-mark-mini": XMarkMini,
}
