export const modules = [
  "api-key",
  "auth",
  "cart",
  "currency",
  "customer",
  "fulfillment",
  "inventory-next",
  "order",
  "payment",
  "pricing",
  "product",
  "promotion",
  "region",
  "sales-channel",
  "stock-location-next",
  "store",
  "tax",
  "translation",
  "user",
]

const allReferences = [
  ...modules,
  "core-flows",
  "auth-provider",
  "dml",
  "file",
  "fulfillment-provider",
  "helper-steps",
  "js-sdk",
  "medusa",
  "modules-sdk",
  "notification",
  "payment-provider",
  "tax-provider",
  "types",
  "utils",
  "workflows",
  "locking",
  "cache",
  "caching",
  "event",
  "file-service",
  "notification-service",
  "events",
  "module-events",
  "analytics",
  "analytics-provider",
]

export default allReferences
