post:
  operationId: PostProductCategoriesCategoryProductsBatch
  summary: Add Products to a category
  description: Assign a batch of products to a product category.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product Category.
      schema:
        type: string
    - in: query
      name: expand
      description: (Comma separated) Category fields to be expanded in the response.
      schema:
        type: string
    - in: query
      name: fields
      description: (Comma separated) Category fields to be retrieved in the response.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/AdminPostProductCategoriesCategoryProductsBatchReq.yaml
  x-codegen:
    method: addProducts
    queryParams: AdminPostProductCategoriesCategoryProductsBatchParams
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: >-
          ../code_samples/JavaScript/product-categories_{id}_products_batch/post.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-categories_{id}_products_batch/post.sh
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Category
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductCategoriesCategoryRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
delete:
  operationId: DeleteProductCategoriesCategoryProductsBatch
  summary: Delete Products
  description: Remove a list of products from a product category.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product Category.
      schema:
        type: string
    - in: query
      name: expand
      description: (Comma separated) Category fields to be expanded in the response.
      schema:
        type: string
    - in: query
      name: fields
      description: (Comma separated) Category fields to be retrieved in the response.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/AdminDeleteProductCategoriesCategoryProductsBatchReq.yaml
  x-codegen:
    method: removeProducts
    queryParams: AdminDeleteProductCategoriesCategoryProductsBatchParams
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: >-
          ../code_samples/JavaScript/product-categories_{id}_products_batch/delete.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-categories_{id}_products_batch/delete.sh
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Category
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductCategoriesCategoryRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
