delete:
  operationId: DeleteProductCategoriesCategory
  summary: Delete a Product Category
  description: Deletes a ProductCategory.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product Category
      schema:
        type: string
  x-codegen:
    method: delete
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/product-categories_{id}/delete.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-categories_{id}/delete.sh
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Category
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductCategoriesCategoryDeleteRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
get:
  operationId: GetProductCategoriesCategory
  summary: Get a Product Category
  description: Retrieves a Product Category.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product Category
      schema:
        type: string
    - in: query
      name: expand
      description: (Comma separated) Which fields should be expanded in the results.
      schema:
        type: string
    - in: query
      name: fields
      description: (Comma separated) Which fields should be included in the results.
      schema:
        type: string
  x-codegen:
    method: retrieve
    queryParams: AdminGetProductCategoryParams
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/product-categories_{id}/get.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-categories_{id}/get.sh
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Category
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductCategoriesCategoryRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
post:
  operationId: PostProductCategoriesCategory
  summary: Update a Product Category
  description: Updates a Product Category.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product Category.
      schema:
        type: string
    - in: query
      name: expand
      description: >-
        (Comma separated) Which fields should be expanded in each product
        category.
      schema:
        type: string
    - in: query
      name: fields
      description: >-
        (Comma separated) Which fields should be retrieved in each product
        category.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AdminPostProductCategoriesCategoryReq.yaml
  x-codegen:
    method: update
    queryParams: AdminPostProductCategoriesCategoryParams
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/product-categories_{id}/post.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-categories_{id}/post.sh
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Category
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductCategoriesCategoryRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
