export const cartFieldsForRefreshSteps = [
  "region_id",
  "currency_code",
  "region.*",
  "items.*",
  "items.tax_lines.*",
  "shipping_address.*",
  "shipping_methods.*",
  "shipping_methods.tax_lines*",
  "customer.*",
  "customer.groups.*",
]

export const completeCartFields = [
  "id",
  "currency_code",
  "email",
  "created_at",
  "updated_at",
  "total",
  "subtotal",
  "tax_total",
  "discount_total",
  "discount_tax_total",
  "original_total",
  "original_tax_total",
  "item_total",
  "item_subtotal",
  "item_tax_total",
  "sales_channel_id",
  "original_item_total",
  "original_item_subtotal",
  "original_item_tax_total",
  "shipping_total",
  "shipping_subtotal",
  "shipping_tax_total",
  "original_shipping_tax_total",
  "original_shipping_tax_subtotal",
  "original_shipping_total",
  "items.*",
  "items.tax_lines.*",
  "items.adjustments.*",
  "customer.*",
  "shipping_methods.*",
  "shipping_methods.tax_lines.*",
  "shipping_methods.adjustments.*",
  "shipping_address.*",
  "billing_address.*",
  "region.*",
  "payment_collection.*",
  "payment_collection.payment_sessions.*",

  "items.variants.id",
  "items.variants.title",
  "items.variants.sku",
  "items.variants.barcode",
  "items.variants.manage_inventory",
  "items.variants.allow_backorder",
  "items.variants.product.id",
  "items.variants.product.title",
  "items.variants.product.description",
  "items.variants.product.subtitle",
  "items.variants.product.thumbnail",
  "items.variants.product.type",
  "items.variants.product.collection",
  "items.variants.product.handle",

  "items.variants.calculated_price.calculated_amount",

  "items.variants.inventory_items.inventory_item_id",
  "items.variants.inventory_items.required_quantity",

  "items.variants.inventory_items.inventory.location_levels.stock_locations.id",
  "items.variants.inventory_items.inventory.location_levels.stock_locations.name",

  "items.variants.inventory_items.inventory.location_levels.stock_locations.sales_channels.id",
  "items.variants.inventory_items.inventory.location_levels.stock_locations.sales_channels.name",
]
