import { CloudAnalysisResult, CloudDispatchPayload } from "../types/index.js"

export class CloudContextBuilder {
  build(payload: CloudDispatchPayload): CloudAnalysisResult {
    const claudePrompt = this.buildPrompt(payload)

    return {
      affectedProjects: [
        {
          project: "cloud",
          reason:
            "User-facing dashboard changes were deployed to Cloud Production",
        },
      ],
      claudePrompt,
      featureFlaggedFeatures: payload.featureFlaggedFeatures ?? [],
    }
  }

  private buildPrompt(payload: CloudDispatchPayload): string {
    const sections: string[] = []

    sections.push(this.buildSkillSection())
    sections.push(this.buildTaskSection())
    sections.push(
      this.buildDescriptionsSection(
        payload.descriptions,
        payload.featureFlaggedFeatures ?? []
      )
    )
    sections.push(this.buildAffectedProjectSection())
    sections.push(this.buildConstraintsSection())

    return sections.join("\n\n---\n\n")
  }

  private buildSkillSection(): string {
    return `## Instructions

Use the /writing-docs skill before making any documentation changes. Load the \`reference/cloud-style.md\` reference file from that skill — it contains the rules and patterns for writing Medusa Cloud documentation correctly.`
  }

  private buildTaskSection(): string {
    return `## Task

A new version of Medusa Cloud was deployed to production. The section below describes the user-facing dashboard changes that were shipped.

Your job is to:
1. Load the /writing-docs skill and read \`reference/cloud-style.md\`
2. Review the feature descriptions below
3. For each described change, determine whether a documentation update is needed
4. If an existing page covers the feature, update it to reflect the new or changed behavior
5. If a new feature has no existing page and is substantial enough to warrant one, create it and add it to \`www/apps/cloud/sidebar.mjs\`
6. If a described change is too vague or clearly internal, skip it rather than guess`
  }

  private buildDescriptionsSection(
    descriptions: string,
    featureFlaggedFeatures: string[]
  ): string {
    const lines: string[] = [
      `## Feature Descriptions`,
      ``,
      `The following describes user-facing changes that were shipped in this deployment. These descriptions were generated by analyzing the dashboard code changes — they contain no source code, only behavioral descriptions.`,
      ``,
      descriptions,
    ]

    if (featureFlaggedFeatures.length > 0) {
      lines.push(``)
      lines.push(
        `> **Note:** The following features appear to be guarded by a feature flag and may not be visible to all users yet: ${featureFlaggedFeatures.map((f) => `**${f}**`).join(", ")}. Document them as normal but be aware they may not be fully released.`
      )
    }

    return lines.join("\n")
  }

  private buildAffectedProjectSection(): string {
    return `## Affected Documentation Project

### cloud

**Project path:** \`www/apps/cloud\`

**Writable directories (only modify files within these):**
- \`www/apps/cloud/app/\`
- \`www/apps/cloud/sidebar.mjs\``
  }

  private buildConstraintsSection(): string {
    return `## Hard Constraints

These are absolute rules. Violating them will cause the workflow to fail:

1. **Only write files within \`www/apps/cloud/app/\`** or \`www/apps/cloud/sidebar.mjs\`
2. **Never modify \`www/apps/cloud/generated/\`** — auto-generated by \`yarn prep\`, which runs automatically after your session
3. **Do not run \`yarn prep\` or \`yarn lint:content\`** — these run automatically after your session ends
4. **Do not invent Cloudinary screenshot URLs** — they can be manually added later if needed.
5. **Do not document internal platform details** — only user-visible behaviors, UI flows, and settings
6. **If a description is too vague to write accurate docs, skip it** rather than guess or fabricate details`
  }
}
