name = "medusa-docs-resources"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[rules]]
type = "ESModule"
globs = ["**/*.mjs"]
