import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1610171629437 implements MigrationInterface {
    name = 'Init1610171629437'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_e078c18a7edd40accfaea4e01c8"`);
        await queryRunner.query(`ALTER TABLE "refund" DROP CONSTRAINT "FK_9615fbcd1030024cc33893a1900"`);
        await queryRunner.query(`DROP INDEX "IDX_723472e41cae44beb0763f4039"`);
        await queryRunner.query(`ALTER TABLE "refund" RENAME COLUMN "currency_code" TO "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "UQ_e078c18a7edd40accfaea4e01c8"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP COLUMN "payment_session_id"`);
        await queryRunner.query(`ALTER TABLE "fulfillment" ADD "idempotency_key" character varying`);
        await queryRunner.query(`ALTER TABLE "payment_session" ADD "is_selected" boolean`);
        await queryRunner.query(`CREATE TYPE "payment_session_status_enum" AS ENUM('authorized', 'pending', 'requires_more', 'error', 'canceled')`);
        await queryRunner.query(`ALTER TABLE "payment_session" ADD "status" "payment_session_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_session" ADD "idempotency_key" character varying`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "idempotency_key" character varying`);
        await queryRunner.query(`ALTER TABLE "cart" ADD "idempotency_key" character varying`);
        await queryRunner.query(`ALTER TABLE "return" ADD "idempotency_key" character varying`);
        await queryRunner.query(`ALTER TABLE "swap" ADD "difference_due" integer`);
        await queryRunner.query(`ALTER TABLE "swap" ADD "confirmed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "swap" ADD "idempotency_key" character varying`);
        await queryRunner.query(`ALTER TABLE "order" ADD "idempotency_key" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "return_item"."is_requested" IS NULL`);
        await queryRunner.query(`ALTER TABLE "return_item" ALTER COLUMN "is_requested" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_717a141f96b76d794d409f38129"`);
        await queryRunner.query(`ALTER TABLE "region" DROP CONSTRAINT "FK_3bdd5896ec93be2f1c62a3309a5"`);
        await queryRunner.query(`ALTER TABLE "money_amount" DROP CONSTRAINT "FK_e15811f81339e4bd8c440aebe1c"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_f41553459a4b1491c9893ebc921"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_55beebaa09e947cccca554af222"`);
        await queryRunner.query(`COMMENT ON COLUMN "currency"."code" IS NULL`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "PK_723472e41cae44beb0763f4039c" PRIMARY KEY ("code")`);
        await queryRunner.query(`COMMENT ON COLUMN "money_amount"."sale_amount" IS NULL`);
        await queryRunner.query(`ALTER TABLE "money_amount" ALTER COLUMN "sale_amount" SET DEFAULT null`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2"`);
        await queryRunner.query(`ALTER TABLE "product_variant" ALTER COLUMN "product_id" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variant"."product_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "discount"."starts_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_484c329f4783be4e18e5e2ff090"`);
        await queryRunner.query(`ALTER TABLE "cart" ALTER COLUMN "region_id" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cart"."region_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "return"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "return" ALTER COLUMN "status" SET DEFAULT 'requested'`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_52dd74e8c989aa5665ad2852b8b"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_ebd3e02011ca6e072302e569d52"`);
        await queryRunner.query(`ALTER TABLE "swap" ALTER COLUMN "order_id" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "swap"."order_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "swap" ALTER COLUMN "return_id" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "swap"."return_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "refund" ALTER COLUMN "idempotency_key" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "refund"."idempotency_key" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`COMMENT ON COLUMN "order"."fulfillment_status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "fulfillment_status" SET DEFAULT 'not_fulfilled'`);
        await queryRunner.query(`COMMENT ON COLUMN "order"."payment_status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "payment_status" SET DEFAULT 'not_paid'`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "request_method" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."request_method" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "request_params" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."request_params" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "request_path" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."request_path" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "response_code" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."response_code" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "response_body" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."response_body" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."recovery_point" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "recovery_point" SET DEFAULT 'started'`);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP CONSTRAINT "PK_0f2bff3bccc785c320a4df836de"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD CONSTRAINT "PK_b4f4b63d1736689b7008980394c" PRIMARY KEY ("store_id")`);
        await queryRunner.query(`DROP INDEX "IDX_82a6bbb0b527c20a0002ddcbd6"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP COLUMN "currency_code"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD "currency_code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP CONSTRAINT "PK_b4f4b63d1736689b7008980394c"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD CONSTRAINT "PK_0f2bff3bccc785c320a4df836de" PRIMARY KEY ("store_id", "currency_code")`);
        await queryRunner.query(`CREATE INDEX "IDX_82a6bbb0b527c20a0002ddcbd6" ON "store_currencies" ("currency_code") `);
        await queryRunner.query(`ALTER TABLE "payment_session" ADD CONSTRAINT "OneSelected" UNIQUE ("cart_id", "is_selected")`);
        await queryRunner.query(`ALTER TABLE "fulfillment" ADD CONSTRAINT "FK_a52e234f729db789cf473297a5c" FOREIGN KEY ("swap_id") REFERENCES "swap"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "region" ADD CONSTRAINT "FK_3bdd5896ec93be2f1c62a3309a5" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "money_amount" ADD CONSTRAINT "FK_e15811f81339e4bd8c440aebe1c" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_f41553459a4b1491c9893ebc921" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_484c329f4783be4e18e5e2ff090" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_52dd74e8c989aa5665ad2852b8b" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_ebd3e02011ca6e072302e569d52" FOREIGN KEY ("return_id") REFERENCES "return"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_717a141f96b76d794d409f38129" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_55beebaa09e947cccca554af222" FOREIGN KEY ("default_currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_55beebaa09e947cccca554af222"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_717a141f96b76d794d409f38129"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_ebd3e02011ca6e072302e569d52"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_52dd74e8c989aa5665ad2852b8b"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_484c329f4783be4e18e5e2ff090"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_f41553459a4b1491c9893ebc921"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2"`);
        await queryRunner.query(`ALTER TABLE "money_amount" DROP CONSTRAINT "FK_e15811f81339e4bd8c440aebe1c"`);
        await queryRunner.query(`ALTER TABLE "region" DROP CONSTRAINT "FK_3bdd5896ec93be2f1c62a3309a5"`);
        await queryRunner.query(`ALTER TABLE "fulfillment" DROP CONSTRAINT "FK_a52e234f729db789cf473297a5c"`);
        await queryRunner.query(`ALTER TABLE "payment_session" DROP CONSTRAINT "OneSelected"`);
        await queryRunner.query(`DROP INDEX "IDX_82a6bbb0b527c20a0002ddcbd6"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP CONSTRAINT "PK_0f2bff3bccc785c320a4df836de"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD CONSTRAINT "PK_b4f4b63d1736689b7008980394c" PRIMARY KEY ("store_id")`);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP COLUMN "currency_code"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD "currency_code" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_82a6bbb0b527c20a0002ddcbd6" ON "store_currencies" ("currency_code") `);
        await queryRunner.query(`ALTER TABLE "store_currencies" DROP CONSTRAINT "PK_b4f4b63d1736689b7008980394c"`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD CONSTRAINT "PK_0f2bff3bccc785c320a4df836de" PRIMARY KEY ("currency_code", "store_id")`);
        await queryRunner.query(`ALTER TABLE "store_currencies" ADD CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60" FOREIGN KEY ("currency_code") REFERENCES "currency"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "recovery_point" SET DEFAULT 'string'`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."recovery_point" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."response_body" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "response_body" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."response_code" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "response_code" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."request_path" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "request_path" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."request_params" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "request_params" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "idempotency_key"."request_method" IS NULL`);
        await queryRunner.query(`ALTER TABLE "idempotency_key" ALTER COLUMN "request_method" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "payment_status" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "order"."payment_status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "fulfillment_status" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "order"."fulfillment_status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "order"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "refund"."idempotency_key" IS NULL`);
        await queryRunner.query(`ALTER TABLE "refund" ALTER COLUMN "idempotency_key" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "swap"."return_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "swap" ALTER COLUMN "return_id" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "swap"."order_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "swap" ALTER COLUMN "order_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_ebd3e02011ca6e072302e569d52" FOREIGN KEY ("return_id") REFERENCES "return"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_52dd74e8c989aa5665ad2852b8b" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "return"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cart"."region_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cart" ALTER COLUMN "region_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_484c329f4783be4e18e5e2ff090" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "discount"."starts_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variant"."product_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "product_variant" ALTER COLUMN "product_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "money_amount" ALTER COLUMN "sale_amount" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "money_amount"."sale_amount" IS NULL`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "PK_723472e41cae44beb0763f4039c"`);
        await queryRunner.query(`COMMENT ON COLUMN "currency"."code" IS NULL`);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_55beebaa09e947cccca554af222" FOREIGN KEY ("default_currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_f41553459a4b1491c9893ebc921" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "money_amount" ADD CONSTRAINT "FK_e15811f81339e4bd8c440aebe1c" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "region" ADD CONSTRAINT "FK_3bdd5896ec93be2f1c62a3309a5" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_717a141f96b76d794d409f38129" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_item" ALTER COLUMN "is_requested" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "return_item"."is_requested" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP COLUMN "confirmed_at"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP COLUMN "difference_due"`);
        await queryRunner.query(`ALTER TABLE "return" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "payment_session" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "payment_session" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "payment_session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_session" DROP COLUMN "is_selected"`);
        await queryRunner.query(`ALTER TABLE "fulfillment" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "cart" ADD "payment_session_id" character varying`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "UQ_e078c18a7edd40accfaea4e01c8" UNIQUE ("payment_session_id")`);
        await queryRunner.query(`ALTER TABLE "currency" ADD "id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "refund" RENAME COLUMN "idempotency_key" TO "currency_code"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_723472e41cae44beb0763f4039" ON "currency" ("code") `);
        await queryRunner.query(`ALTER TABLE "refund" ADD CONSTRAINT "FK_9615fbcd1030024cc33893a1900" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_e078c18a7edd40accfaea4e01c8" FOREIGN KEY ("payment_session_id") REFERENCES "payment_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
