import {MigrationInterface, QueryRunner} from "typeorm";

export class addLineItemAdjustments1646832251674 implements MigrationInterface {
    name = 'addLineItemAdjustments1646832251674'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."return_reason" DROP CONSTRAINT "FK_2250c5d9e975987ab212f61a657"`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" DROP CONSTRAINT "FK_5bd11d0e2a9628128e2c26fd0a6"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP CONSTRAINT "FK_2484cf14c437a04586b07e7dddb"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP CONSTRAINT "FK_ece65a774192b34253abc4cd672"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP CONSTRAINT "FK_346e0016cf045b9980747747645"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP CONSTRAINT "FK_f672727ab020df6c50fb64c1a70"`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" DROP CONSTRAINT "FK_8aaa78ba90d3802edac317df869"`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" DROP CONSTRAINT "FK_3a6947180aeec283cd92c59ebb0"`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" DROP CONSTRAINT "FK_c556e14eff4d6f03db593df955e"`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" DROP CONSTRAINT "FK_37f361c38a18d12a3fa3158d0cf"`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" DROP CONSTRAINT "FK_2212515ba306c79f42c46a99db7"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" DROP CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" DROP CONSTRAINT "FK_21683a063fe82dafdf681ecc9c4"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" DROP CONSTRAINT "FK_be66106a673b88a81c603abe7eb"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" DROP CONSTRAINT "FK_4e0739e5f0244c08d41174ca08a"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" DROP CONSTRAINT "FK_f4194aa81073f3fab8aa86906ff"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" DROP CONSTRAINT "FK_a21a7ffbe420d492eb46c305fec"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" DROP CONSTRAINT "FK_8df75ef4f35f217768dc1135458"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" DROP CONSTRAINT "FK_6680319ebe1f46d18f106191d59"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" DROP CONSTRAINT "FK_d38047a90f3d42f0be7909e8aea"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" DROP CONSTRAINT "FK_0fb38b6d167793192bc126d835e"`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" DROP CONSTRAINT "FK_e7b488cebe333f449398769b2cc"`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" DROP CONSTRAINT "FK_0fc1ec4e3db9001ad60c19daf16"`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" DROP CONSTRAINT "FK_f2bb9f71e95b315eb24b2b84cb3"`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" DROP CONSTRAINT "FK_e62ff11e4730bb3adfead979ee2"`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" DROP CONSTRAINT "FK_dc9bbf9fcb9ba458d25d512811b"`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" DROP CONSTRAINT "FK_c2c0f3edf39515bd15432afe6e5"`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" DROP CONSTRAINT "FK_b4f4b63d1736689b7008980394c"`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" DROP CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60"`);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" DROP CONSTRAINT "FK_620330964db8d2999e67b0dbe3e"`);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" DROP CONSTRAINT "FK_3c6412d076292f439269abe1a23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_346e0016cf045b998074774764"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f672727ab020df6c50fb64c1a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2484cf14c437a04586b07e7ddd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d04aebeabb6a89f87e536a124"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ece65a774192b34253abc4cd67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25a3138bb236f63d9bb6c8ff11"`);
        await queryRunner.query(`CREATE TABLE "line_item_adjustment" ("id" character varying NOT NULL, "rate" real NOT NULL, "name" character varying NOT NULL, "code" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb, "item_id" character varying NOT NULL, "description" character varying NOT NULL, "resource_id" character varying, "amount" integer NOT NULL, CONSTRAINT "PK_2b1360103753df2dc8257c2c8c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be9aea2ccf3567007b6227da4d" ON "line_item_adjustment" ("item_id") `);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "public"."product_option" DROP CONSTRAINT "FK_e634fca34f6b594b87fdbee95f6"`);
        await queryRunner.query(`ALTER TABLE "public"."product_option" ALTER COLUMN "product_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."discount" ALTER COLUMN "starts_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."draft_order_status_enum" RENAME TO "draft_order_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."draft_order_status_enum" AS ENUM('open', 'completed')`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ALTER COLUMN "status" TYPE "public"."draft_order_status_enum" USING "status"::"text"::"public"."draft_order_status_enum"`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "public"."draft_order_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "public"."fulfillment" DROP CONSTRAINT "FK_beb35a6de60a6c4f91d5ae57e44"`);
        await queryRunner.query(`ALTER TABLE "public"."fulfillment" ALTER COLUMN "provider_id" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_2484cf14c437a04586b07e7ddd" ON "public"."product_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d04aebeabb6a89f87e536a124" ON "public"."product_tax_rate" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ece65a774192b34253abc4cd67" ON "public"."product_type_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_25a3138bb236f63d9bb6c8ff11" ON "public"."product_type_tax_rate" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_346e0016cf045b998074774764" ON "public"."shipping_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f672727ab020df6c50fb64c1a7" ON "public"."shipping_tax_rate" ("shipping_option_id") `);
        await queryRunner.query(`ALTER TABLE "public"."product_option" ADD CONSTRAINT "FK_e634fca34f6b594b87fdbee95f6" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD CONSTRAINT "FK_f672727ab020df6c50fb64c1a70" FOREIGN KEY ("shipping_option_id") REFERENCES "shipping_option"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD CONSTRAINT "FK_346e0016cf045b9980747747645" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD CONSTRAINT "FK_2484cf14c437a04586b07e7dddb" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD CONSTRAINT "FK_ece65a774192b34253abc4cd672" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."return_reason" ADD CONSTRAINT "FK_f633ee140342a719d984c358e26" FOREIGN KEY ("parent_return_reason_id") REFERENCES "return_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "line_item_adjustment" ADD CONSTRAINT "FK_be9aea2ccf3567007b6227da4d2" FOREIGN KEY ("item_id") REFERENCES "line_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ADD CONSTRAINT "FK_5bd11d0e2a9628128e2c26fd0a6" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."fulfillment" ADD CONSTRAINT "FK_beb35a6de60a6c4f91d5ae57e44" FOREIGN KEY ("provider_id") REFERENCES "fulfillment_provider"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."note" ADD CONSTRAINT "FK_665a6b343c55b13e2aba74ef613" FOREIGN KEY ("author_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" ADD CONSTRAINT "FK_8aaa78ba90d3802edac317df869" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" ADD CONSTRAINT "FK_3a6947180aeec283cd92c59ebb0" FOREIGN KEY ("provider_id") REFERENCES "payment_provider"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" ADD CONSTRAINT "FK_c556e14eff4d6f03db593df955e" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" ADD CONSTRAINT "FK_37f361c38a18d12a3fa3158d0cf" FOREIGN KEY ("provider_id") REFERENCES "fulfillment_provider"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" ADD CONSTRAINT "FK_2212515ba306c79f42c46a99db7" FOREIGN KEY ("image_id") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" ADD CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" ADD CONSTRAINT "FK_21683a063fe82dafdf681ecc9c4" FOREIGN KEY ("product_tag_id") REFERENCES "product_tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" ADD CONSTRAINT "FK_4e0739e5f0244c08d41174ca08a" FOREIGN KEY ("discount_rule_id") REFERENCES "discount_rule"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" ADD CONSTRAINT "FK_be66106a673b88a81c603abe7eb" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" ADD CONSTRAINT "FK_f4194aa81073f3fab8aa86906ff" FOREIGN KEY ("discount_id") REFERENCES "discount"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" ADD CONSTRAINT "FK_a21a7ffbe420d492eb46c305fec" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" ADD CONSTRAINT "FK_6680319ebe1f46d18f106191d59" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" ADD CONSTRAINT "FK_8df75ef4f35f217768dc1135458" FOREIGN KEY ("discount_id") REFERENCES "discount"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" ADD CONSTRAINT "FK_d38047a90f3d42f0be7909e8aea" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" ADD CONSTRAINT "FK_0fb38b6d167793192bc126d835e" FOREIGN KEY ("gift_card_id") REFERENCES "gift_card"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" ADD CONSTRAINT "FK_e7b488cebe333f449398769b2cc" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" ADD CONSTRAINT "FK_0fc1ec4e3db9001ad60c19daf16" FOREIGN KEY ("discount_id") REFERENCES "discount"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" ADD CONSTRAINT "FK_e62ff11e4730bb3adfead979ee2" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" ADD CONSTRAINT "FK_f2bb9f71e95b315eb24b2b84cb3" FOREIGN KEY ("gift_card_id") REFERENCES "gift_card"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" ADD CONSTRAINT "FK_c2c0f3edf39515bd15432afe6e5" FOREIGN KEY ("item_id") REFERENCES "claim_item"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" ADD CONSTRAINT "FK_dc9bbf9fcb9ba458d25d512811b" FOREIGN KEY ("tag_id") REFERENCES "claim_tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" ADD CONSTRAINT "FK_b4f4b63d1736689b7008980394c" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" ADD CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" ADD CONSTRAINT "FK_620330964db8d2999e67b0dbe3e" FOREIGN KEY ("customer_group_id") REFERENCES "customer_group"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" ADD CONSTRAINT "FK_3c6412d076292f439269abe1a23" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" DROP CONSTRAINT "FK_3c6412d076292f439269abe1a23"`);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" DROP CONSTRAINT "FK_620330964db8d2999e67b0dbe3e"`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" DROP CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60"`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" DROP CONSTRAINT "FK_b4f4b63d1736689b7008980394c"`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" DROP CONSTRAINT "FK_dc9bbf9fcb9ba458d25d512811b"`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" DROP CONSTRAINT "FK_c2c0f3edf39515bd15432afe6e5"`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" DROP CONSTRAINT "FK_f2bb9f71e95b315eb24b2b84cb3"`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" DROP CONSTRAINT "FK_e62ff11e4730bb3adfead979ee2"`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" DROP CONSTRAINT "FK_0fc1ec4e3db9001ad60c19daf16"`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" DROP CONSTRAINT "FK_e7b488cebe333f449398769b2cc"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" DROP CONSTRAINT "FK_0fb38b6d167793192bc126d835e"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" DROP CONSTRAINT "FK_d38047a90f3d42f0be7909e8aea"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" DROP CONSTRAINT "FK_8df75ef4f35f217768dc1135458"`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" DROP CONSTRAINT "FK_6680319ebe1f46d18f106191d59"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" DROP CONSTRAINT "FK_a21a7ffbe420d492eb46c305fec"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" DROP CONSTRAINT "FK_f4194aa81073f3fab8aa86906ff"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" DROP CONSTRAINT "FK_be66106a673b88a81c603abe7eb"`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" DROP CONSTRAINT "FK_4e0739e5f0244c08d41174ca08a"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" DROP CONSTRAINT "FK_21683a063fe82dafdf681ecc9c4"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" DROP CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e"`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" DROP CONSTRAINT "FK_2212515ba306c79f42c46a99db7"`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" DROP CONSTRAINT "FK_37f361c38a18d12a3fa3158d0cf"`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" DROP CONSTRAINT "FK_c556e14eff4d6f03db593df955e"`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" DROP CONSTRAINT "FK_3a6947180aeec283cd92c59ebb0"`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" DROP CONSTRAINT "FK_8aaa78ba90d3802edac317df869"`);
        await queryRunner.query(`ALTER TABLE "public"."note" DROP CONSTRAINT "FK_665a6b343c55b13e2aba74ef613"`);
        await queryRunner.query(`ALTER TABLE "public"."fulfillment" DROP CONSTRAINT "FK_beb35a6de60a6c4f91d5ae57e44"`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" DROP CONSTRAINT "FK_5bd11d0e2a9628128e2c26fd0a6"`);
        await queryRunner.query(`ALTER TABLE "line_item_adjustment" DROP CONSTRAINT "FK_be9aea2ccf3567007b6227da4d2"`);
        await queryRunner.query(`ALTER TABLE "public"."return_reason" DROP CONSTRAINT "FK_f633ee140342a719d984c358e26"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP CONSTRAINT "FK_ece65a774192b34253abc4cd672"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP CONSTRAINT "FK_2484cf14c437a04586b07e7dddb"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP CONSTRAINT "FK_346e0016cf045b9980747747645"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP CONSTRAINT "FK_f672727ab020df6c50fb64c1a70"`);
        await queryRunner.query(`ALTER TABLE "public"."product_option" DROP CONSTRAINT "FK_e634fca34f6b594b87fdbee95f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f672727ab020df6c50fb64c1a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_346e0016cf045b998074774764"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25a3138bb236f63d9bb6c8ff11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ece65a774192b34253abc4cd67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d04aebeabb6a89f87e536a124"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2484cf14c437a04586b07e7ddd"`);
        await queryRunner.query(`ALTER TABLE "public"."fulfillment" ALTER COLUMN "provider_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."fulfillment" ADD CONSTRAINT "FK_beb35a6de60a6c4f91d5ae57e44" FOREIGN KEY ("provider_id") REFERENCES "fulfillment_provider"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."draft_order_status_enum_old" AS ENUM('open', 'awaiting', 'completed')`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ALTER COLUMN "status" TYPE "public"."draft_order_status_enum_old" USING "status"::"text"::"public"."draft_order_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "public"."draft_order_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."draft_order_status_enum_old" RENAME TO "draft_order_status_enum"`);
        await queryRunner.query(`ALTER TABLE "public"."discount" ALTER COLUMN "starts_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."product_option" ALTER COLUMN "product_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."product_option" ADD CONSTRAINT "FK_e634fca34f6b594b87fdbee95f6" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "IDX_be9aea2ccf3567007b6227da4d"`);
        await queryRunner.query(`DROP TABLE "line_item_adjustment"`);
        await queryRunner.query(`CREATE INDEX "IDX_25a3138bb236f63d9bb6c8ff11" ON "public"."product_type_tax_rate" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ece65a774192b34253abc4cd67" ON "public"."product_type_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d04aebeabb6a89f87e536a124" ON "public"."product_tax_rate" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2484cf14c437a04586b07e7ddd" ON "public"."product_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f672727ab020df6c50fb64c1a7" ON "public"."shipping_tax_rate" ("shipping_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_346e0016cf045b998074774764" ON "public"."shipping_tax_rate" ("rate_id") `);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" ADD CONSTRAINT "FK_3c6412d076292f439269abe1a23" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."customer_group_customers" ADD CONSTRAINT "FK_620330964db8d2999e67b0dbe3e" FOREIGN KEY ("customer_group_id") REFERENCES "customer_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" ADD CONSTRAINT "FK_82a6bbb0b527c20a0002ddcbd60" FOREIGN KEY ("currency_code") REFERENCES "currency"("code") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."store_currencies" ADD CONSTRAINT "FK_b4f4b63d1736689b7008980394c" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" ADD CONSTRAINT "FK_c2c0f3edf39515bd15432afe6e5" FOREIGN KEY ("item_id") REFERENCES "claim_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."claim_item_tags" ADD CONSTRAINT "FK_dc9bbf9fcb9ba458d25d512811b" FOREIGN KEY ("tag_id") REFERENCES "claim_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" ADD CONSTRAINT "FK_e62ff11e4730bb3adfead979ee2" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order_gift_cards" ADD CONSTRAINT "FK_f2bb9f71e95b315eb24b2b84cb3" FOREIGN KEY ("gift_card_id") REFERENCES "gift_card"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" ADD CONSTRAINT "FK_0fc1ec4e3db9001ad60c19daf16" FOREIGN KEY ("discount_id") REFERENCES "discount"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order_discounts" ADD CONSTRAINT "FK_e7b488cebe333f449398769b2cc" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" ADD CONSTRAINT "FK_0fb38b6d167793192bc126d835e" FOREIGN KEY ("gift_card_id") REFERENCES "gift_card"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."cart_gift_cards" ADD CONSTRAINT "FK_d38047a90f3d42f0be7909e8aea" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" ADD CONSTRAINT "FK_6680319ebe1f46d18f106191d59" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."cart_discounts" ADD CONSTRAINT "FK_8df75ef4f35f217768dc1135458" FOREIGN KEY ("discount_id") REFERENCES "discount"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" ADD CONSTRAINT "FK_a21a7ffbe420d492eb46c305fec" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."discount_regions" ADD CONSTRAINT "FK_f4194aa81073f3fab8aa86906ff" FOREIGN KEY ("discount_id") REFERENCES "discount"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" ADD CONSTRAINT "FK_4e0739e5f0244c08d41174ca08a" FOREIGN KEY ("discount_rule_id") REFERENCES "discount_rule"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."discount_rule_products" ADD CONSTRAINT "FK_be66106a673b88a81c603abe7eb" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" ADD CONSTRAINT "FK_21683a063fe82dafdf681ecc9c4" FOREIGN KEY ("product_tag_id") REFERENCES "product_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_tags" ADD CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" ADD CONSTRAINT "FK_2212515ba306c79f42c46a99db7" FOREIGN KEY ("image_id") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" ADD CONSTRAINT "FK_37f361c38a18d12a3fa3158d0cf" FOREIGN KEY ("provider_id") REFERENCES "fulfillment_provider"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."region_fulfillment_providers" ADD CONSTRAINT "FK_c556e14eff4d6f03db593df955e" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" ADD CONSTRAINT "FK_3a6947180aeec283cd92c59ebb0" FOREIGN KEY ("provider_id") REFERENCES "payment_provider"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."region_payment_providers" ADD CONSTRAINT "FK_8aaa78ba90d3802edac317df869" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD CONSTRAINT "FK_f672727ab020df6c50fb64c1a70" FOREIGN KEY ("shipping_option_id") REFERENCES "shipping_option"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."shipping_tax_rate" ADD CONSTRAINT "FK_346e0016cf045b9980747747645" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_type_tax_rate" ADD CONSTRAINT "FK_ece65a774192b34253abc4cd672" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."product_tax_rate" ADD CONSTRAINT "FK_2484cf14c437a04586b07e7dddb" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ADD CONSTRAINT "FK_5bd11d0e2a9628128e2c26fd0a6" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."return_reason" ADD CONSTRAINT "FK_2250c5d9e975987ab212f61a657" FOREIGN KEY ("parent_return_reason_id") REFERENCES "return_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
