import { medusaIntegrationTestRunner } from "@medusajs/test-utils"
import {
  createStoreCreditAccountsWorkflow,
  creditAccountsWorkflow,
  debitAccountsWorkflow,
} from "@medusajs/loyalty-plugin/workflows"
import {
  IStoreCreditModuleService,
  PluginModule,
} from "@medusajs/loyalty-plugin/types"
import {
  adminHeaders,
  createAdminUser,
  generatePublishableKey,
  generateStoreHeaders,
} from "../../../../helpers/create-admin-user"
import { createAuthenticatedCustomer } from "../../../helpers/create-authenticated-customer"

jest.setTimeout(60 * 1000)

medusaIntegrationTestRunner({
  testSuite: ({ dbConnection, api, getContainer, dbUtils }) => {
    let customer, storeCreditAccount, storeHeaders

    beforeAll(async () => {
      await createAdminUser(dbConnection, adminHeaders, getContainer())
      const publishableKey = await generatePublishableKey(getContainer())
      storeHeaders = generateStoreHeaders({ publishableKey })

      const user = await createAuthenticatedCustomer(api, storeHeaders, {
        email: "initial@customer.com",
      })
      storeHeaders.headers["Authorization"] = `Bearer ${user.jwt}`
      customer = user.customer

      const { result: storeCreditAccounts } =
        await createStoreCreditAccountsWorkflow.run({
          input: [
            {
              customer_id: customer.id,
              currency_code: "USD",
            },
          ],
          container: getContainer(),
        })

      storeCreditAccount = storeCreditAccounts[0]

      await dbUtils.snapshot()
    })

    describe("debitAccountsWorkflow", () => {
      beforeEach(async () => {
        await creditAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 100,
              reference: "test",
              reference_id: "test-id",
            },
          ],
          container: getContainer(),
        })
      })

      it("successfully debits the account", async () => {
        const { result: transactions } = await debitAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 100,
              reference: "test",
              reference_id: "test-id",
            },
          ],
          container: getContainer(),
        })

        expect(transactions).toEqual([
          expect.objectContaining({
            account_id: storeCreditAccount.id,
            amount: 100,
            reference: "test",
            reference_id: "test-id",
          }),
        ])
      })

      it("should throw if the amount is greater than the account balance", async () => {
        const { errors } = await debitAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 201,
              reference: "test",
              reference_id: "test-id",
            },
          ],
          container: getContainer(),
          throwOnError: false,
        })

        expect(errors).toEqual([
          expect.objectContaining({
            error: expect.objectContaining({
              message: "Insufficient balance",
              type: "invalid_data",
            }),
          }),
        ])
      })

      it("should throw if account does not exist", async () => {
        const { errors } = await debitAccountsWorkflow.run({
          input: [
            {
              account_id: "does-not-exist",
              amount: 201,
              reference: "test",
              reference_id: "test-id",
            },
          ],
          container: getContainer(),
          throwOnError: false,
        })

        expect(errors).toEqual([
          expect.objectContaining({
            error: expect.objectContaining({
              message:
                "StoreCreditAccount with id: does-not-exist was not found",
              type: "not_found",
            }),
          }),
        ])
      })

      it("should throw if amount does not exist", async () => {
        const { errors } = await debitAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              reference: "test",
              reference_id: "test-id",
            },
          ],
          container: getContainer(),
          throwOnError: false,
        })

        expect(errors).toEqual([
          expect.objectContaining({
            error: expect.objectContaining({
              message: "Amount is required",
              type: "invalid_data",
            }),
          }),
        ])
      })
    })

    describe("retrieveAccountStats", () => {
      // `softDeleteAccountTransactions` is generated by `MedusaService` but is
      // not declared on `IStoreCreditModuleService`.
      let storeCreditModule: IStoreCreditModuleService & {
        softDeleteAccountTransactions: (ids: string[]) => Promise<void>
      }

      beforeEach(() => {
        storeCreditModule = getContainer().resolve(PluginModule.STORE_CREDIT)
      })

      it("should return a zero balance for an account without transactions", async () => {
        const stats = await storeCreditModule.retrieveAccountStats({
          account_id: storeCreditAccount.id,
        })

        expect(stats).toEqual({
          id: storeCreditAccount.id,
          balance: 0,
          credits: 0,
          debits: 0,
        })
      })

      it("should exclude soft deleted transactions from the balance", async () => {
        const { result: credits } = await creditAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 100,
              reference: "test",
              reference_id: "test-id",
            },
            {
              account_id: storeCreditAccount.id,
              amount: 50,
              reference: "test",
              reference_id: "test-id-2",
            },
          ],
          container: getContainer(),
        })

        const { result: debits } = await debitAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 30,
              reference: "test",
              reference_id: "test-id-3",
            },
          ],
          container: getContainer(),
        })

        await storeCreditModule.softDeleteAccountTransactions([credits[1].id])

        expect(
          await storeCreditModule.retrieveAccountStats({
            account_id: storeCreditAccount.id,
          })
        ).toEqual({
          id: storeCreditAccount.id,
          balance: 70,
          credits: 100,
          debits: 30,
        })

        await storeCreditModule.softDeleteAccountTransactions([debits[0].id])

        expect(
          await storeCreditModule.retrieveAccountStats({
            account_id: storeCreditAccount.id,
          })
        ).toEqual({
          id: storeCreditAccount.id,
          balance: 100,
          credits: 100,
          debits: 0,
        })
      })

      it("should not spend the value of a soft deleted credit", async () => {
        const { result: credits } = await creditAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 100,
              reference: "test",
              reference_id: "test-id",
            },
          ],
          container: getContainer(),
        })

        await storeCreditModule.softDeleteAccountTransactions([credits[0].id])

        const { errors } = await debitAccountsWorkflow.run({
          input: [
            {
              account_id: storeCreditAccount.id,
              amount: 100,
              reference: "test",
              reference_id: "test-id-2",
            },
          ],
          container: getContainer(),
          throwOnError: false,
        })

        expect(errors).toEqual([
          expect.objectContaining({
            error: expect.objectContaining({
              message: "Insufficient balance",
              type: "invalid_data",
            }),
          }),
        ])
      })
    })
  },
})
