import { PluginDetails } from "@medusajs/types"
import fs from "fs/promises"
import path from "path"

type PackageJson = {
  exports?: unknown
}

async function readInstalledPackageJson(
  packageName: string,
  fromDir: string
): Promise<PackageJson | null> {
  try {
    const pkgJsonPath = require.resolve(
      path.join(packageName, "package.json"),
      { paths: [fromDir] }
    )
    return JSON.parse(await fs.readFile(pkgJsonPath, "utf-8"))
  } catch {
    return null
  }
}

/**
 * Whether `value` (an `exports` entry) contains a `types` condition, directly
 * or nested inside other conditions (`import` / `require` / `default` / `node`…).
 */
function hasTypesCondition(value: unknown): boolean {
  if (!value || typeof value !== "object") {
    return false
  }
  const record = value as Record<string, unknown>
  if (typeof record.types === "string") {
    return true
  }
  return Object.values(record).some(hasTypesCondition)
}

function exposesRootTypes(pkg: PackageJson): boolean {
  const exportsMap = pkg.exports
  if (exportsMap && typeof exportsMap === "object") {
    const rootExport = (exportsMap as Record<string, unknown>)["."]
    if (hasTypesCondition(rootExport)) {
      return true
    }
  }
  return false
}

/**
 * Writes `<directory>/.medusa/types/medusa-env.d.ts` with a
 * `/// <reference types="…" />` directive for each installed plugin whose
 * package exposes root types.
 *
 * Local plugins are skipped: they live in the project's `src`, so the project
 * tsconfig already sees them.
 */
export async function generateMedusaEnvTypes({
  directory,
  plugins,
}: {
  directory: string
  plugins: PluginDetails[]
}): Promise<void> {
  const pluginPackages: string[] = []

  for (const plugin of plugins) {
    const packageName = plugin.name

    if (pluginPackages.includes(packageName)) {
      continue
    }

    const pkg = await readInstalledPackageJson(packageName, directory)

    if (pkg && exposesRootTypes(pkg)) {
      pluginPackages.push(packageName)
    }
  }

  const referenceLines = pluginPackages
    .map((name) => `/// <reference types="${name}" />`)
    .join("\n")

  const banner = [
    "// medusa-env.d.ts",
    "// Auto-generated by Medusa — do not edit manually.",
    "// Re-generated on `medusa build` and `medusa develop`.",
    "",
  ].join("\n")

  const content =
    pluginPackages.length > 0
      ? `${banner}${referenceLines}\n`
      : `${banner}// No plugin type packages detected.\nexport {}\n`

  const outputDir = path.join(directory, ".medusa", "types")
  await fs.mkdir(outputDir, { recursive: true })
  await fs.writeFile(path.join(outputDir, "medusa-env.d.ts"), content, "utf-8")
}
