import { LoadedModule, PluginDetails } from "@medusajs/types"
import { existsSync } from "fs"
import fs from "fs/promises"
import path from "path"
import { promiseAll } from "../common/promise-all"
import { MODULE_PACKAGE_NAMES } from "./definition"

type PackageJson = {
  name: string
  exports?: unknown
  types?: string
  typings?: string
}

async function readInstalledPackageJson(
  packageName: string,
  fromDir: string
): Promise<PackageJson | null> {
  try {
    const pkgJsonPath = require.resolve(
      path.join(packageName, "package.json"),
      { paths: [fromDir] }
    )
    return JSON.parse(await fs.readFile(pkgJsonPath, "utf-8"))
  } catch {
    return null
  }
}

/**
 * Whether `value` (an `exports` entry) contains a `types` condition, directly
 * or nested inside other conditions (`import` / `require` / `default` / `node`…).
 */
function hasTypesCondition(value: unknown): boolean {
  if (!value || typeof value !== "object") {
    return false
  }
  const record = value as Record<string, unknown>
  if (typeof record.types === "string") {
    return true
  }
  return Object.values(record).some(hasTypesCondition)
}

function exposesRootTypes(pkg: PackageJson): boolean {
  if (typeof pkg.types === "string" || typeof pkg.typings === "string") {
    return true
  }

  const exportsMap = pkg.exports
  if (exportsMap && typeof exportsMap === "object") {
    const rootExport = (exportsMap as Record<string, unknown>)["."]
    if (hasTypesCondition(rootExport)) {
      return true
    }
  }
  return false
}

function resolvesToTypes(specifier: string, fromDir: string): boolean {
  try {
    const resolved = require.resolve(specifier, { paths: [fromDir] })
    if (/\.d\.[cm]?ts$/.test(resolved)) {
      return true
    }

    const declaration = resolved.replace(/\.[cm]?js$/, ".d.ts")
    return existsSync(declaration)
  } catch {
    return false
  }
}

async function shipsRootTypes(
  specifier: string,
  directory: string
): Promise<boolean> {
  const pkg = await readInstalledPackageJson(specifier, directory)
  if (pkg && exposesRootTypes(pkg)) {
    return true
  }

  return resolvesToTypes(specifier, directory)
}

function isBareSpecifier(specifier: unknown): specifier is string {
  return (
    typeof specifier === "string" &&
    !specifier.startsWith("./") &&
    !specifier.startsWith("../") &&
    !path.isAbsolute(specifier)
  )
}

function getModuleReferenceSpecifier(module: LoadedModule): string | undefined {
  const definition = module.__definition
  const resolvePath = definition?.resolvePath
  const canonical = MODULE_PACKAGE_NAMES[definition?.key]

  if (canonical) {
    return isBareSpecifier(resolvePath) &&
      resolvePath.startsWith("@medusajs/medusa/")
      ? resolvePath
      : canonical
  }

  return isBareSpecifier(resolvePath) ? resolvePath : undefined
}

function collectCandidates(
  plugins: PluginDetails[],
  modules: Record<string, LoadedModule | LoadedModule[]>
): string[] {
  const specifiers = new Set<string>()

  for (const plugin of plugins) {
    specifiers.add(plugin.name)
  }

  for (const value of Object.values(modules)) {
    const services = Array.isArray(value) ? value : [value]

    for (const service of services) {
      const specifier = getModuleReferenceSpecifier(service)
      if (specifier) {
        specifiers.add(specifier)
      }
    }
  }

  return Array.from(specifiers)
}

/**
 * Writes `<directory>/.medusa/types/augmentation-refs.d.ts` with a
 * `/// <reference types="…" />` directive for each installed plugin and each
 * loaded core/package module that exposes types.
 */
export async function generateAugmentationRefs({
  directory,
  plugins,
  modules,
}: {
  directory: string
  plugins: PluginDetails[]
  modules?: Record<string, LoadedModule | LoadedModule[]>
}): Promise<void> {
  const candidates = collectCandidates(plugins, modules ?? {})

  const checked = await promiseAll(
    candidates.map(async (resolvePath) => ({
      resolvePath,
      shipsTypes: await shipsRootTypes(resolvePath, directory),
    }))
  )

  const references = checked
    .filter((entry) => entry.shipsTypes)
    .map((entry) => entry.resolvePath)

  const referenceLines = references
    .map((name) => `/// <reference types="${name}" />`)
    .join("\n")

  const banner = [
    "// augmentation-refs.d.ts",
    "// Auto-generated by Medusa — do not edit manually.",
    "// Re-generated on `medusa build` and `medusa develop`.",
    "",
  ].join("\n")

  const content =
    references.length > 0
      ? `${banner}${referenceLines}\n`
      : `${banner}// No plugin or module type packages detected.\nexport {}\n`

  const outputDir = path.join(directory, ".medusa", "types")
  await fs.mkdir(outputDir, { recursive: true })
  await fs.writeFile(
    path.join(outputDir, "augmentation-refs.d.ts"),
    content,
    "utf-8"
  )
}
