type: object
description: The layout configuration's details.
x-schemaName: AdminLayoutConfiguration
required:
  - id
  - zone
  - user_id
  - is_system_default
  - configuration
  - created_at
  - updated_at
properties:
  id:
    type: string
    title: id
    description: The layout configuration's ID.
  zone:
    type: string
    title: zone
    description: The layout configuration's zone.
  user_id:
    type: string
    title: user_id
    description: The ID of the user who created the layout configuration.
  is_system_default:
    type: boolean
    title: is_system_default
    description: Whether the layout configuration is a system default.
  configuration:
    type: object
    description: The configuration's details.
    required:
      - widgets
    properties:
      widgets:
        type: object
        description: >-
          The configurations of the widgets in the layout. The object's keys are
          the widget IDs, and the values are objects containing the widget's
          configuration details.
        additionalProperties:
          type: object
          properties:
            hidden:
              type: boolean
              title: hidden
              description: Whether the widget is hidden.
            section:
              type: string
              title: section
              description: The section of the layout where the widget is placed.
            order:
              type: number
              title: order
              description: The widget's order.
  created_at:
    type: string
    format: date-time
    title: created_at
    description: The date the layout configuration was created.
  updated_at:
    type: string
    format: date-time
    title: updated_at
    description: The date the layout configuration was last updated.
