import { buildAllowedFields } from "../utils/allowed-fields"

export const defaultStoreProductFields = [
  "id",
  "title",
  "subtitle",
  "description",
  "handle",
  "is_giftcard",
  "discountable",
  "thumbnail",
  "collection_id",
  "type_id",
  "weight",
  "length",
  "height",
  "width",
  "hs_code",
  "origin_country",
  "mid_code",
  "material",
  "created_at",
  "updated_at",
  "*type",
  "*collection",
  "*options",
  "*options.values",
  "*tags",
  "*images",
  "*variants",
  "*variants.options",
]

export const allowedStoreProductExtraFields = [
  "metadata",
  "categories",
  "status",
  "external_id",
  "deleted_at",
  "variants.calculated_price",
  "variants.inventory_quantity",
  "variants.manage_inventory",
  "variants.allow_backorder",
  "variants.images",
  "variants.thumbnail",
  "variants.options.option",
  "variants.inventory_items",
  "variants.inventory_items.inventory",
  "variants.prices",
  "variants.id",
  "variants.title",
  "variants.sku",
  "variants.barcode",
  "variants.ean",
  "variants.upc",
  "variants.hs_code",
  "variants.origin_country",
  "variants.mid_code",
  "variants.material",
  "variants.weight",
  "variants.length",
  "variants.height",
  "variants.width",
  "variants.created_at",
  "variants.updated_at",
  "variants.deleted_at",
  "variants.options.id",
  "variants.options.value",
  "options.id",
  "options.title",
  "options.is_exclusive",
  "options.values.id",
  "options.values.value",
  "images.id",
  "images.url",
  "images.rank",
  "type.id",
  "type.value",
  "type.created_at",
  "type.updated_at",
  "tags.id",
  "tags.value",
  "tags.created_at",
  "tags.updated_at",
  "collection.id",
  "collection.title",
  "collection.handle",
  "collection.created_at",
  "collection.updated_at",
  "collection.deleted_at",
  "collection.metadata",
]

export const retrieveProductQueryConfig = {
  defaults: defaultStoreProductFields,
  allowed: buildAllowedFields(
    defaultStoreProductFields,
    allowedStoreProductExtraFields
  ),
  storeRelationsLimit: 4,
  isList: false,
}

export const listProductQueryConfig = {
  ...retrieveProductQueryConfig,
  defaultLimit: 50,
  isList: true,
}
