import fs from "fs/promises"
import { outdent } from "outdent"
import path from "path"

function getEntryModule() {
  return outdent`
        /**
         * This file was automatically generated by Medusa.
         * Any changes to this file will be overwritten.
         */
        import { render } from "@medusajs/dashboard";
        import extensions from "virtual:medusa/extensions";
        import "./index.css";

        render(
            document.getElementById("medusa"),
            {
                extensions
            }
        )

        if (import.meta.hot) {
            import.meta.hot.accept();
        }
    `
}

function getHtmlTemplate() {
  return outdent`
        <!doctype html>
        <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
            <link rel="icon" href="data:," data-placeholder-favicon />
        </head>

        <body>
            <div id="medusa"></div>
            <script type="module" src="./app.tsx"></script>
        </body>
        </html>
    `
}

function getCssTemplate() {
  return outdent`
    @import "@medusajs/dashboard/css";

    @tailwind base;
    @tailwind components;
    @tailwind utilities;
  `
}

export async function writeStaticFiles() {
  const outputDir = path.resolve(process.cwd(), ".medusa/client")

  await fs.mkdir(outputDir, { recursive: true })

  await fs.writeFile(path.resolve(outputDir, "app.tsx"), getEntryModule())
  await fs.writeFile(path.resolve(outputDir, "index.html"), getHtmlTemplate())
  await fs.writeFile(path.resolve(outputDir, "index.css"), getCssTemplate())
}
