export const modules = [
  "api-key",
  "auth",
  "cart",
  "currency",
  "customer",
  "inventory",
  "inventory-next",
  "payment",
  "pricing",
  "product",
  "promotion",
  "region",
  "sales-channel",
  "stock-location",
  "stock-location-next",
  "store",
  "tax",
  "user",
]

const allReferences = [
  ...modules,
  "entities",
  "file",
  "fulfillment",
  "js-client",
  "medusa-config",
  "medusa-react",
  "medusa",
  "notification",
  "payment-processor",
  "payment-provider",
  "price-selection",
  "search",
  "services",
  "tax-calculation",
  "tax-provider",
  "tax-service",
  "types",
  "utils",
  "workflows",
]

export default allReferences
