export enum ChangeActionType {
  CANCEL = "CANCEL",
  CANCEL_RETURN = "CANCEL_RETURN",
  FULFILL_ITEM = "FULFILL_ITEM",
  CANCEL_ITEM_FULFILLMENT = "CANCEL_ITEM_FULFILLMENT",
  ITEM_ADD = "ITEM_ADD",
  ITEM_REMOVE = "ITEM_REMOVE",
  RECEIVE_DAMAGED_RETURN_ITEM = "RECEIVE_DAMAGED_RETURN_ITEM",
  RECEIVE_RETURN_ITEM = "RECEIVE_RETURN_ITEM",
  RETURN_ITEM = "RETURN_ITEM",
  SHIPPING_ADD = "SHIPPING_ADD",
  SHIP_ITEM = "SHIP_ITEM",
  WRITE_OFF_ITEM = "WRITE_OFF_ITEM",
}
